import { 
  Building2, 
  BookOpen, 
  HeartPulse, 
  HardHat, 
  Landmark, 
  Map, 
  Users, 
  Palette, 
  Trophy, 
  TreePine, 
  ShieldAlert, 
  LayoutDashboard 
} from 'lucide-react';
import { SecretariatInfo, Post } from './types';

export const SECRETARIATS: SecretariatInfo[] = [
  { id: 'principal', name: 'Portal Principal', icon: LayoutDashboard },
  { id: 'administracao', name: 'Administração', icon: Building2 },
  { id: 'educacao', name: 'Educação', icon: BookOpen },
  { id: 'saude', name: 'Saúde', icon: HeartPulse },
  { id: 'obras', name: 'Obras e Planejamento', icon: HardHat },
  { id: 'fazenda', name: 'Fazenda e Finanças', icon: Landmark },
  { id: 'turismo', name: 'Turismo', icon: Map },
  { id: 'social', name: 'Assistência Social', icon: Users },
  { id: 'cultura', name: 'Cultura', icon: Palette },
  { id: 'esportes', name: 'Esportes', icon: Trophy },
  { id: 'meio_ambiente', name: 'Meio Ambiente', icon: TreePine },
  { id: 'seguranca', name: 'Segurança e Trânsito', icon: ShieldAlert },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: '1',
    secretariatId: 'saude',
    title: 'Campanha de Vacinação Contra a Gripe',
    content: 'A campanha começará na próxima segunda-feira em todos os postos de saúde da cidade. Público alvo: idosos e crianças.\n\nPor favor, levem a carteira de vacinação.',
    imageUrl: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&q=80&w=800',
    isImportant: true,
    isForInstagram: true,
    isForBlog: true,
    createdAt: new Date().toISOString(),
    author: 'João Silva',
  },
  {
    id: '4',
    secretariatId: 'educacao',
    title: 'Entrega de Kits Escolares 2026',
    content: 'A partir do dia 15, iniciaremos a distribuição dos kits de material escolar e uniformes para toda a rede municipal de ensino infantil e fundamental. O cronograma completo está disponível na intranet.',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800',
    isImportant: true,
    isForInstagram: true,
    isForBlog: true,
    createdAt: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
    author: 'Profa. Helena',
  },
  {
    id: '5',
    secretariatId: 'administracao',
    title: 'Recadastramento Anual de Servidores',
    content: 'Atenção servidores! O período de recadastramento anual obrigatório começa na próxima semana. O processo será 100% digital através do portal do servidor no Brotas 360.',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800',
    isImportant: true,
    isForInstagram: false,
    isForBlog: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    author: 'RH Brotas',
  },
  {
    id: '12',
    secretariatId: 'saude',
    title: 'Boletim Semanal da Dengue',
    content: 'Os casos de dengue reduziram 15% esta semana devido ao trabalho intensivo dos agentes de endemias. Continuaremos com a nebulização nos bairros da zona leste.',
    imageUrl: 'https://images.unsplash.com/photo-1584362917165-526a968579e8?auto=format&fit=crop&q=80&w=800',
    isImportant: false,
    isForInstagram: false,
    isForBlog: true,
    createdAt: new Date(Date.now() - 10000000).toISOString(),
    author: 'Vigilância Epidemiológica',
  },
  {
    id: '6',
    secretariatId: 'fazenda',
    title: 'Prazo final para cota única do IPTU',
    content: 'Lembramos que o prazo para pagamento do IPTU com 10% de desconto em cota única vence no último dia útil deste mês. As guias podem ser emitidas no site.',
    imageUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&q=80&w=800',
    isImportant: true,
    isForInstagram: true,
    isForBlog: true,
    createdAt: new Date(Date.now() - 43200000).toISOString(), // 12 hours ago
    author: 'Setor de Tributos',
  },
  {
    id: '7',
    secretariatId: 'social',
    title: 'Atualização do CadÚnico e Benefícios',
    content: 'O CRAS Central estará fazendo um mutirão neste sábado para atualização do Cadastro Único e pesagem do Bolsa Família. Mobilizem os assistidos nos bairros.',
    imageUrl: 'https://images.unsplash.com/photo-1593113589914-075568e09151?auto=format&fit=crop&q=80&w=800',
    isImportant: false,
    isForInstagram: true,
    isForBlog: false,
    createdAt: new Date(Date.now() - 50400000).toISOString(),
    author: 'Marcos Assistente',
  },
  {
    id: '8',
    secretariatId: 'cultura',
    title: 'Nova Exposição: "Memórias de Brotas"',
    content: 'O Centro Cultural inaugura nesta sexta-feira a exposição fotográfica retratando o século XX na nossa cidade. Excelente pauta para as redes sociais.',
    imageUrl: 'https://images.unsplash.com/photo-1518998053401-878c73562a36?auto=format&fit=crop&q=80&w=800',
    isImportant: false,
    isForInstagram: true,
    isForBlog: true,
    createdAt: new Date(Date.now() - 60400000).toISOString(),
    author: 'Diretoria de Cultura',
  },
  {
    id: '2',
    secretariatId: 'turismo',
    title: 'Festival de Inverno de Brotas 2026',
    content: 'Estão abertas as inscrições para comerciantes locais que desejam montar barracas no festival.\nO evento ocorrerá na Praça Central.',
    imageUrl: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&q=80&w=800',
    isImportant: true,
    isForInstagram: true,
    isForBlog: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    author: 'Maria Souza',
  },
  {
    id: '3',
    secretariatId: 'obras',
    title: 'Recapeamento da Avenida Marginal',
    content: 'Informamos que a Avenida Marginal passará por recapeamento durante as próximas duas semanas. Atenção aos desvios sinalizados e rotas alternativas.',
    imageUrl: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?auto=format&fit=crop&q=80&w=800',
    isImportant: false,
    isForInstagram: false,
    isForBlog: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    author: 'Carlos Almeida',
  },
  {
    id: '9',
    secretariatId: 'esportes',
    title: 'Inscrições Abertas: Campeonato de Futsal',
    content: 'O 15º Campeonato Municipal de Futsal está com inscrições abertas até dia 20. Categorias de base e principal. Regulamento na aba de documentos deste portal.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
    isImportant: true,
    isForInstagram: true,
    isForBlog: true,
    createdAt: new Date(Date.now() - 286400000).toISOString(),
    author: 'Secretaria de Esportes',
  },
  {
    id: '10',
    secretariatId: 'meio_ambiente',
    title: 'Mutirão de Plantio no Parque dos Saltos',
    content: 'Neste fim de semana, teremos o plantio de 200 mudas de árvores nativas no Parque dos Saltos, como parte do projeto de recuperação ciliar. Toda equipe da prefeitura está convidada a participar!',
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    isImportant: false,
    isForInstagram: true,
    isForBlog: true,
    createdAt: new Date(Date.now() - 386400000).toISOString(),
    author: 'Eng. Ambiental Roberto',
  },
  {
    id: '11',
    secretariatId: 'seguranca',
    title: 'Nova Sinalização Semafórica no Centro',
    content: 'Atenção aos novos semáforos instalados no cruzamento da Av. Rodolpho Guimarães. O período educativo vai durar 7 dias. O setor de comunicação deve avisar a população amplamente.',
    imageUrl: 'https://images.unsplash.com/photo-1634816353986-778ea23f9976?auto=format&fit=crop&q=80&w=800',
    isImportant: true,
    isForInstagram: true,
    isForBlog: true,
    createdAt: new Date(Date.now() - 486400000).toISOString(),
    author: 'Guarda Municipal',
  }
];
